[instances.default]
type = "p3.8xlarge"
ami_id = "ami-019266bf7a55994a7"
username = "ubuntu"
volume_size = 100

[commands.provision]
lazy = true
copy_to = ["build/"]
command = "bash build/provision.sh"

[commands.train]
depends_on = "provision"
copy_to = ["model", "build"]
command = "bash build/train.sh"
copy_from = ["model.onnx"]

[commands.notebook]
copy_to =["model", "build"]
command = "jupyter lab"
forward_ports = {'8080'= '8888'}

[commands.tensorboard]
command = "pkill tensorboard || ~/.local/bin/tensorboard --logdir model_logs/default/"
forward_ports = {'6006' = '6006'}
