---
Description: ALPHA - Model resources ofr imagesim project

Parameters:
  DataBucketName:
    Type: String
    Description: The name of the bucket for this model
    Default: imagesim-storage

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref DataBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Component
          Value: imagesim
        - Key: Contact
          Value: ateam@maxar.com
        - Key: Department
          Value: analytics
        - Key: Environment
          Value: dev
        - Key: Name
          Value: imagesim-storage-bucket
        - Key: Project
          Value: od-cd

Outputs:
  ImagesimBucket:
    Value: !Ref DataBucket
    Description: The name of the s3 bucket for imagesim data
